user-message: "WARNING: This stack project is generated."

resolver: nightly-2023-12-05

# We have 8 packages.
packages:
  - ./persistent
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-qq
  - ./persistent-redis
  - ./persistent-sqlite
  - ./persistent-test

extra-deps: []
